title: Y-G Jung
description: Personal website
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed

<script type="text/javascript"
  id="MathJax-script"
  async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
